### ISSUE TITLE
filter or sort people by category in people list

### ISSUE THREAD

**Issue by kristinoc** [eventespresso/eea-people-addon#15]
Issue: user has very long list [100+] of staff added to the "People add-on" which becomes very cumbersome when in the event editor as this requires that you scroll the page and visually search through over 100 entries to find the people to check off to add to page.

As a workaround, we recommended this user try using taxonomies to apply a type to people, but that does not solve issue since they all still show in the list:

here is the scenario this user tried /reported:
1) I created two "Types" of people. 
· Program Coordinator and
· Speakers
2) I assigned people to Program Coordinator and to Speaker. The speakers are not assigned to Program Coordinator type and vice versa.
3) When I go to the edit event page and "Assign Program Coordinator" or "Assign Speaker" everyone's name shows up on both lists. (See Attached)

[https://secure.helpscout.net/conversation/671477248/570454/]

Suggested resolution:  add a way to filter or just populate with people added to a specific category.

**Comment by nerrad** [comment]
Related issue to this is #6 (what I write here is essentially explained in that issue as well).

It's important to highlight the distinction between assigning types to a person in the person editor vs assigning a person to a type in the Event editor.  In the person editor there is this description:

> When you assign a person to a people type here, it just indicates that this person fulfills that role in your organization and this person will be listed on the archive page for that person type.

In other words, this is just the role the person fills for the entire organization.  It never was intended to indicate the types a person could be assigned to for each event.  The relationship of person to type here applies to the archive pages for the type when listing the type archive on the frontend of the site.

In the event editor, every person is shown with each available type because its entirely possible someone that is categorized as as specific type for the entire organization might still serve in a specific role for a specific event.  So if we filter the people for these types in the event editor to only show the people assigned to those types globally, then there's no way to assign them to a different type for just that event.  When people are assigned to a type in the event editor that's JUST for that event and they won't be listed on any archive page for that type (unless they are also assigned to that type globally via the person editor).

So currently, things are working as intended that way (which doesn't mean it can't be changed).

Now there are certainly things we can do to deal with the issue of having so many people show up in metaboxes in the event editor but I think we need to be wary about removing the intended purpose for how type assigning goes currently.  Some things we can do:

* Add a toggle in the event editor for each "type" metabox to filter the list to only people assigned to those types globally.
* Include some sort of autocomplete/search to allow for filtering by given string.
* Include some ajax/REST paging for the view.

I'm not sure what direction is desired here and whether folks want to revisit the intended behaviour for types as described so I'll give it to you @joshfeck for now?

**Comment by nerrad** [comment]
Bumped the estimate to 100 because between planning and implementation of any of the ideas suggested, it's a bit more effort than initially estimated (still some unknowns).
